[DRUP-803] Real fix for the module uninstall problem + test coverage
apigee/apigee-edge-drupal pull request #203
Opened 2019-05-23 15:54 UTC by mxr576

As it was revealed the real problem with the module uninstall is caused by a Drupal core bug:
https://github.com/apigee/apigee-edge-drupal/pull/198#discussion_r286904065

This PR reverts the unnecessary changes and adds workarounds for the Drupal core. Also contains tests for the module uninstall process.

Latest test on Travis CI: https://travis-ci.org/mxr576/apigee-devportal-drupal/builds/536363114

2019-05-23 17:17 UTC, cnovak requested changes
We don't want to add try/catch blocks just to follow a different pattern than what core is doing.  Adding tests are a good idea, but we need to focus on getting features out the door instead of fixing solved problems in different ways.

2019-05-24 05:34 UTC, mxr576 commented
> We don't want to add try/catch blocks just to follow a different pattern than what core is doing.

@cnovak I think you are misunderstanding what is going on here :) In Drupal core, you may not see this pattern* (which is bad, because hiding object dependencies is anti-pattern) but this problem is not about where do you retrieve entity storages from entity type manager in a class and why.
I know [this was a lengthy comment](https://github.com/apigee/apigee-edge-drupal/pull/198#discussion_r286904065) but if you [check the video](https://drive.google.com/file/d/1jQKtoMerpQXvuRQtQ_2KReJVl7u62lu1/view) in the end and read [the Drupal core issue's description](https://www.drupal.org/project/drupal/issues/3056604) you should understand the change in b49093a592

```php
<?php
class ResponseSubscriber implements EventSubscriberInterface {

  /**
   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
   */
  private $entity_type_manager;

  /**
   * ResponseSubscriber constructor.
   *
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager
   */
  public function __construct(EntityTypeManagerInterface $entityTypeManager) {
    $this->entity_type_manager = $entityTypeManager;
  }

  /**
   * Does something with foo entities.
   *
   * @param \Symfony\Component\HttpKernel\Event\FilterResponseEvent $event
   *   The event.
   */
  public function handle(FilterResponseEvent $event) {
    $foo_entities = $this->entity_type_manager->getStorage('foo')->loadMultiple();
    // TODO Do something with foo entities.
  }

  /**
   * {@inheritdoc}
   */
  public static function getSubscribedEvents() {
    $events[KernelEvents::RESPONSE][] = ['handle'];
    return $events;
  }

}
```
and this

```php
<?php
  /**
   * ResponseSubscriber constructor.
   *
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager
   */
  public function __construct(EntityTypeManagerInterface $entityTypeManager) {
    $this->fooStorage = $entityTypeManager->getStorage('foo');
  }

  /**
   * Does something with foo entities.
   *
   * @param \Symfony\Component\HttpKernel\Event\FilterResponseEvent $event
   *   The event.
   */
  public function handle(FilterResponseEvent $event) {
    $foo_entities = $this->fooStorage->loadMultiple();
    // TODO Do something with foo entities.
  }
```
fails exactly the same way with Drupal 8.7. So it does not matter where do you retrieve the entity storage  instance, until 3056604 has not been fixed in Drupal core. 

Consequently, [this change](https://github.com/apigee/apigee-edge-drupal/commit/b49093a592c1077dbe283367ad889dc230721f13) does not fix anything, it just works _at this moment_ because of the `TeamStatusWarningSubscriber` does not run on the module listing page. Otherwise, it would fail the same way as before.

Compared this with my fix which actually provides a proper temporary workaround for the Drupal core bug which could be easily followed in the new event subscribers and it could be removed when the Drupal core bug gets fixed.

2019-05-24 11:47 UTC, mxr576 commented
Fixed failing Apigee Edge uninstall test because of dependencies. New test build: https://travis-ci.org/mxr576/apigee-devportal-drupal/builds/536737890

2019-05-24 11:49 UTC, mxr576 commented
@Jaesin Let's continue the discussion about this if you still disagree, shall we?
![image](https://user-images.githubusercontent.com/1755573/58325678-c88e3580-7e2a-11e9-92c9-1cdc7f347e80.png)

https://github.com/apigee/apigee-edge-drupal/pull/198#discussion_r287224672

2019-05-27 11:32 UTC, mxr576 commented
I have a working patch for the Drupal core bug which is in review at this moment. Added that instead of the workaround that I implemented.

https://travis-ci.org/mxr576/apigee-devportal-drupal/builds/537746931

2019-05-27 13:11 UTC, mxr576 commented
The previous test also passed, but I updated to patch so updated this PR as well.
https://travis-ci.org/mxr576/apigee-devportal-drupal/builds/537781480

2019-05-27 14:50 UTC, mxr576 commented
Well, interesting. Apigee Edge tests passed with the 18 patch but failed with the 23 from the Drupal issue. Exactly the inverse happened on Drupal.org :) So the perfect location of the event subscriber unregistration should be in-between.

2019-05-29 05:39 UTC, mxr576 commented
https://travis-ci.org/mxr576/apigee-devportal-drupal/builds/538575563

2020-05-05 18:18 UTC, cnovak commented
The API Docs module was removed some time back, closing issue

2020-05-05 18:18 UTC, closed without merging