[#284] Analytics "chart" shows ranges but no series.
apigee/apigee-edge-drupal pull request #286
Opened 2019-10-24 22:55 UTC by minnur

Fix for https://github.com/apigee/apigee-edge-drupal/issues/284

Changed routine to determine earliest and the latest timestamps.

2019-10-25 07:42 UTC, mxr576 commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
How this change is related to the fix of the problem? Does not this break the responsive support of the chart?

2019-10-25 07:42 UTC, mxr576 commented on src/Form/AppAnalyticsFormBase.php
> +            'min' => !empty($analytics['TimeUnit']) ? min($analytics['TimeUnit']) : 0,
Can you confirm that this fix works every time? It seems odd that a simple change like this can replace a complex calculation.

2019-10-25 07:44 UTC, minnur commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
100% doesn't make it responsive.

2019-10-25 07:45 UTC, minnur commented on src/Form/AppAnalyticsFormBase.php
> +            'min' => !empty($analytics['TimeUnit']) ? min($analytics['TimeUnit']) : 0,
No need for a complex routine here. We just need to find minimum and maximum value from the data list and set those as a threshold

2019-10-25 07:46 UTC, mxr576 commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
But it is still a relative value and if this change is not related to the fix of the bug we should rather keep it untouched.

2019-10-25 07:47 UTC, minnur commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
900 vs 100% is a big difference in what you see in on the page. We now display 0 values in the chart, not just non-zero values.

2019-10-25 07:55 UTC, mxr576 commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
Can you demonstrate the difference with screenshots?

2019-10-25 07:57 UTC, mxr576 commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
> Width of the chart, in pixels.Type: numberDefault: width of the containing element

So what happens if we do not specify the width?

2019-10-25 08:11 UTC, minnur commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
Same as if it would be with 100% value.

2019-10-25 08:28 UTC, mxr576 commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
Yeah, this is what I thought so, but I am still curious about what difference a user can see if the value is 900 or "with of the containing element", for example with the Bartik theme.

2019-10-29 00:55 UTC, cnovak requested changes
Works great showing proper 0 values, here is my data:

```
Date,"Message count"
"2019-10-29 00:00:00 +00:00",8
"2019-10-28 23:00:00 +00:00",12
"2019-10-28 22:00:00 +00:00",12
"2019-10-28 21:00:00 +00:00",10
"2019-10-28 20:00:00 +00:00",45
"2019-10-28 19:00:00 +00:00",0
"2019-10-28 18:00:00 +00:00",0
"2019-10-28 17:00:00 +00:00",0
"2019-10-28 16:00:00 +00:00",1
"2019-10-28 15:00:00 +00:00",0
"2019-10-28 14:00:00 +00:00",0
"2019-10-28 13:00:00 +00:00",0
"2019-10-28 12:00:00 +00:00",0
"2019-10-28 11:00:00 +00:00",0
"2019-10-28 10:00:00 +00:00",0
"2019-10-28 09:00:00 +00:00",0
"2019-10-28 08:00:00 +00:00",0
"2019-10-28 07:00:00 +00:00",0
"2019-10-28 06:00:00 +00:00",0
"2019-10-28 05:00:00 +00:00",0
"2019-10-28 04:00:00 +00:00",0
"2019-10-28 03:00:00 +00:00",0
"2019-10-28 02:00:00 +00:00",0
"2019-10-28 01:00:00 +00:00",0
"2019-10-28 00:00:00 +00:00",0

```

<img width="1603" alt="Screen Shot 2019-10-28 at 5 54 28 PM" src="https://user-images.githubusercontent.com/613093/67728840-05e38a00-f9ac-11e9-9bc8-03f76740a7e9.png">


However, we should not be changing the width to a fixed width as far as I can see.

2019-10-29 00:55 UTC, cnovak commented on src/Form/AppAnalyticsFormBase.php
> +        'width' => '900',
I agree with @mxr576, I do not see any issues on how it renders on different themes using 100%.  If we stick to fixed width, smaller and larger sizes will be stuck using 900px. What problem is a fixed width fixing?

Here is 100% on a few themes, it is rendering correctly as the screen width changes:

<img width="1282" alt="Screen Shot 2019-10-28 at 5 46 50 PM" src="https://user-images.githubusercontent.com/613093/67728733-8fdf2300-f9ab-11e9-821a-d9c6165f8494.png">
<img width="1096" alt="Screen Shot 2019-10-28 at 5 47 39 PM" src="https://user-images.githubusercontent.com/613093/67728734-91a8e680-f9ab-11e9-9f26-23aed9473b54.png">

2019-10-29 01:00 UTC, minnur commented
@cnovak it wasn't showing the whole chart for me with 100% in the kickstarted theme. Making it 900px worked better. I guess this is something that should be address in the kickstarted

2019-10-29 01:07 UTC, minnur commented
I made the change and set the width back to 100%

2019-10-29 03:56 UTC, cnovak commented
> @cnovak it wasn't showing the whole chart for me with 100% in the kickstarter theme. Making it 900px worked better. I guess this is something that should be address in the kickstarter

Yes, agreed, I put in https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/278 about this. I did not see the chart getting cut off on my screen, if you have a screenshot please add to that ticket, thx.

2019-10-29 03:57 UTC, cnovak approved these changes

2019-10-29 03:57 UTC, merged