#320 Fix ApiProduct Entity setProxies() runtime error
apigee/apigee-edge-drupal pull request #323
Opened 2020-01-17 18:28 UTC by cnovak

Add splat operator and tests

Fixes #320

2020-01-22 06:22 UTC, shadcn requested changes
Just a minor phpcs nit. Otherwise this is green to go.

2020-01-22 06:22 UTC, arshad commented on tests/src/Unit/Entity/ApiProductTest.php
> +  /**
Missing short description here.

2020-01-27 16:47 UTC, cnovak commented
@arshad PR ready to review again, fixed phpcs issue

2020-01-27 17:03 UTC, shadcn approved these changes
Looks good. Approved. Thanks @cnovak

2020-01-27 17:03 UTC, merged