Replace Travis CI with CircleCI
apigee/apigee-edge-drupal pull request #337
Opened 2020-02-14 18:06 UTC by arlina-espinoza

This PR replaces the Travis CI integration with CircleCI. Currently only runs the code sniffer - the same job that is running in travis (kernel, functional and JS tests are commented out for now).
To do after this PR: Enable kernel kernel, functional and JS tests - fix any tests that aren't passing.

2020-02-21 16:52 UTC, shadcn approved these changes
Woah this is a major DX win @arlina-espinoza Thank you. LGTM 👍 

Do we have follow up tickets for "To do after this PR: Enable kernel kernel, functional and JS tests - fix any tests that aren't passing."?

2020-02-24 15:40 UTC, cnovak requested changes
Some small requests, and agree w/Arshad that we need issues for remaining tasks.

2020-02-24 15:40 UTC, cnovak commented on phpcs.xml.dist
> +    <rule ref="Drupal.Commenting.GenderNeutralComment.GenderNeutral">
I believe we fixed all comments to conform to this standard, I would rather fix comment than add this.

2020-02-24 15:40 UTC, cnovak commented on .circleci/code-sniffer.sh
> +vendor/bin/phpcs -p -s -n --colors --standard=modules/apigee_edge/phpcs.xml.dist --report=junit --report-junit=artifacts/phpcs/phpcs.xml modules/$1
Do we want to [keep phpmd and phpmetrics](https://github.com/deviantintegral/drupal_tests/blob/master/hooks/code-sniffer.sh#L13)?

2020-02-26 23:24 UTC, arlina-espinoza commented on .circleci/code-sniffer.sh
> +vendor/bin/phpcs -p -s -n --colors --standard=modules/apigee_edge/phpcs.xml.dist --report=junit --report-junit=artifacts/phpcs/phpcs.xml modules/$1
I've re-enabled phpmd and phpmetrics, which do will not throw errors, but give interesting insights into the project. For example:
- https://76-174000098-gh.circle-artifacts.com/0/var/www/html/artifacts/phpmd/index.html
- https://76-174000098-gh.circle-artifacts.com/0/var/www/html/artifacts/phpmetrics/index.html

2020-02-26 23:37 UTC, arlina-espinoza commented on phpcs.xml.dist
> +    <rule ref="Drupal.Commenting.GenderNeutralComment.GenderNeutral">
Re-enabled the `TypeHintMissing` and `GenderNeutralComment` sniffs, and yes, they were passing for the module. :)

2020-02-26 23:41 UTC, arlina-espinoza commented
> Woah this is a major DX win @arlina-espinoza Thank you. LGTM +1
> 
> Do we have follow up tickets for "To do after this PR: Enable kernel kernel, functional and JS tests - fix any tests that aren't passing."?

Added follow up issue to enable other tests here: https://github.com/apigee/apigee-edge-drupal/issues/341

@cnovak I've addressed the requested changes, could you review again, please?

2020-02-28 23:46 UTC, cnovak approved these changes
LGTM

2020-03-02 17:38 UTC, merged