Validate field level constraints on form save
apigee/apigee-edge-drupal pull request #400
Opened 2020-04-21 05:50 UTC by mxr576

Field level constraints are not validated when an instance of a FieldableEdgeEntityForm gets submitted. As FieldableEdgeEntityForm if a fine-tuned copy of ContentEntityForm without being tied to an SQL entity storage, I copied the missing logic from the ContentEntityForm.

Also added a test coverage to the Developer App UI test because by default, this is the only entity with CU UI in the Apigee Edge module (submodules not included) and until this time all "fieldable edge entity" base classes were valided as part of its subclasses' tests, therefore there are no dedicated tests for "fieldable edge entity" base classes.

2020-04-21 10:38 UTC, mxr576 commented
> Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testDeveloperSync
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1'
+'0'

Based on the error message I think it was caused by a MGMT API communication error so I am considering this as a false alarm, but I cannot restart tests anymore.

2020-04-29 05:54 UTC, mxr576 commented
@arshad @arlina-espinoza @cnovak Hi, may I get a review on this?

2020-05-05 08:41 UTC, mxr576 commented
Bumped, this is quite a blocker on some projects :)

2020-05-06 19:40 UTC, arlina-espinoza requested changes
Thanks @mxr576 ! Tested it out locally and works as expected now. The only issue is that the following methods have signatures that are a breaking change for the M10n module. Could they be updated so they don't contain a return value? This is what the m10n module expects:

- public function validateForm(array &$form, FormStateInterface $form_state);
- protected function getEditedFieldNames(FormStateInterface $form_state);
- protected function flagViolations(EntityConstraintViolationListInterface $violations, array $form, FormStateInterface $form_state);

We'd need a follow up task on [apigee-m10n-drupal](https://github.com/apigee/apigee-m10n-drupal) to deprecate the `FieldableMonetizationEntityForm`, as it was previously filling in this functionality, but I don't think that can be done until a 2.x.

2020-05-11 07:48 UTC, arlina-espinoza approved these changes
Thanks for the changes @mxr576 :) It all looks good for me, just a note that the code sniffer validation is failing due to an unrelated Drupal bug that I'm trying to fix here: https://github.com/apigee/apigee-edge-drupal/pull/411

2020-05-11 11:46 UTC, mxr576 commented
@arlina-espinoza Thanks, I saw it. Just let me know when I can rebase this PR.

2020-05-11 17:05 UTC, arlina-espinoza commented
@mxr576 #411 has been merged, so tests should be passing once you rebase. :+1:

2020-05-12 19:27 UTC, arlina-espinoza commented
@googlebot I consent.

2020-05-12 21:47 UTC, merged