[#336] Add Apigee entities display settings
apigee/apigee-edge-drupal pull request #402
Opened 2020-04-24 10:11 UTC by arshad

This PR adds `apigee_edge.display_settings.*` config that any Apigee entity type can extend.

It provides a config form `apigee_edge.display_settings.*` that lets an admin configure the display type for an Apigee edge display. 

Example: the display type for the apps on the `/apps` page.

![Display_settings___Apigee](https://user-images.githubusercontent.com/124599/80201020-8c63e600-8634-11ea-9337-23bf41c3f634.jpg)

This can be extended by any entity type that implements `EntityListBuilder`, i.e all the entity displays such as App, Team Apps, Teams can use this. This also eliminates custom implementation for Rate plans displays in m10n.

## Implementation

```yml
apigee_edge.display_settings.developer_app:
  path: '/admin/config/apigee-edge/app-settings/developer-apps/display-settings'
  defaults:
    _form: '\Drupal\apigee_edge\Form\EdgeEntityDisplaySettingsForm'
    _title: 'Display settings'
    entity_type_id: 'developer_app'
  requirements:
    _permission: 'administer apigee edge'
```

## Theming

When using the display settings, the following templates are available for theming.

`apigee-entity-list.html.twig`
`apigee-entity-list--ENTITY-TYPE.html.twig`
`apigee-entity-list--ENTITY-TYPE--VIEW-MODE.html.twig`

Example:

`apigee-entity-list.html.twig`
`apigee-entity-list--developer-app.html.twig`
`apigee-entity-list--developer-app--collapsible-card.html.twig`

This is WIP and still needs tests.

Fixes #336

2020-04-27 05:10 UTC, mxr576 commented
:+1: for the feature, but isn't is possible to use the same UIs as Drupal provides for other entity types: "Manage display"? With the field management UIs for fieldable entities we tried to follow the same pattern so users with Drupal experience can find what they are looking for easily.

2020-04-27 07:54 UTC, arlina-espinoza commented
Thanks @arshad , this is looking really good! I tested extending the templaates, as well as modifying the variables in a hook preprocess (`hook_preprocess_apigee_entity_list()`), and it all works nicely.
Some notes:
- For this module, I think we'd just need to add the display settings route to the teams listing page. You already covered adding it to the developer apps and team apps.
- @mxr576 Not sure I follow on your comment from above. The Edge entities still have the "manage form display" and "manage display" tabs to configure the display of the entity itself, what is being added is a way to configure the display of the listing of the entities. Drupal core does not provide that for other entities because, well, they use views for that, which we can't :sweat_smile: Perhaps an improvement would be to rename the tab to _"List display settings"_?
![image](https://user-images.githubusercontent.com/4062676/80347467-2daf8f80-8821-11ea-8f13-320cd0123691.png)

2020-04-27 08:13 UTC, arshad commented
Thanks for the review @arlina-espinoza. I'm going to add same for teams listing.

@mxr576 Thanks. So we're still using core field ui and manage display. This is for the `EdgeEntityListBuilder`. It lets you configure which view mode to use for the entity lists.

2020-04-28 17:40 UTC, arshad commented
> For this module, I think we'd just need to add the display settings route to the teams listing page. You already covered adding it to the developer apps and team apps.

@arlina-espinoza This is done. I've also added tests. Ready for review.

2020-04-30 18:52 UTC, arlina-espinoza requested changes
Thanks @arshad , this is looking pretty good. My main feedback is to fix the ListBuilder constructors to avoid a breaking change in the module (posted a link to an example in core).
The other thing I'm not sure is if we should call the tab "Display settings" or something else that makes it clearer that it's to configure the listing of entities, not the individual entities. Any thoughts on this @cnovak ?

2020-04-30 18:52 UTC, arlina-espinoza commented on modules/apigee_edge_teams/src/Entity/ListBuilder/TeamAppListByTeam.php
> +    parent::__construct($entity_type, $entity_type_manager, $config_factory, $render, $request_stack, $time);
This is a breaking change. We should add the `$config_factory` as the last and optional parameter, and instantiate the service if missing during the construct call. See `UserController::_construct()` as an example: https://git.drupalcode.org/project/drupal/-/blob/8.8.x/core/modules/user/src/Controller/UserController.php#L60-97

2020-04-30 18:52 UTC, arlina-espinoza commented on modules/apigee_edge_teams/src/Entity/ListBuilder/TeamAppListByTeam.php
> +        '@label' => $this->entityType->getPluralLabel(),
```suggestion
        '@label' => strtolower($this->entityType->getPluralLabel()),
```

2020-04-30 18:52 UTC, arlina-espinoza commented on src/Entity/ListBuilder/AppListBuilder.php
> +    parent::__construct($entity_type, $entity_type_manager, $config_factory);
See my comment on `TeamAppListByTeam::_construct()` about BC.

2020-04-30 18:52 UTC, arlina-espinoza commented on src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php
> +    parent::__construct($entity_type, $entity_type_manager, $config_factory, $render, $request_stack, $time);
See my comment on `TeamAppListByTeam::_construct()` about BC.

2020-04-30 18:52 UTC, arlina-espinoza commented on src/Entity/ListBuilder/EdgeEntityListBuilder.php
> +  public function __construct(EntityTypeInterface $entity_type, EntityTypeManagerInterface $entity_type_manager, ConfigFactoryInterface $config_factory) {
See my comment on `TeamAppListByTeam::_construct()` about BC.

2020-04-30 18:52 UTC, arlina-espinoza commented on src/Form/EdgeEntityDisplaySettingsForm.php
> +    ];
Should we specify the "Default" is a table listing of entities, with links to entity operations?

2020-05-01 06:20 UTC, arlina-espinoza commented
@googlebot I consent.

2020-05-01 06:22 UTC, arlina-espinoza commented
@arshad I updated a test class and added a `tearDown()` to delete any data that was created if tests were run against a real API connection.

2020-05-04 05:47 UTC, arshad commented
I've implemented the suggestions.

Thanks for the review @arlina-espinoza

2020-05-05 06:22 UTC, arlina-espinoza approved these changes
Thanks @arshad . Tested out locally and LGTM. :wink:

2020-05-05 08:36 UTC, merged