Auth from error message
apigee/apigee-edge-drupal pull request #41
Opened 2018-07-09 12:10 UTC by peterserfozo

2018-07-10 11:37 UTC, mxr576 approved these changes

2018-07-10 11:38 UTC, mxr576 commented
Let's hold back with merging this until this solution gets confirmed by @cnovak in the JIRA user story.

2018-07-10 12:22 UTC, tamasd approved these changes

2018-07-12 10:32 UTC, mxr576 commented on config/schema/apigee_edge.schema.yml
> +      label: 'Client-side validation error message if a Callback URL does not match'
Missing new line in the end of the file.

2018-07-12 10:33 UTC, mxr576 commented on tests/src/Functional/EdgeAuthenticationTest.php
> +    'dblog',
Why it is required?

2018-07-12 10:33 UTC, mxr576 commented on tests/src/Functional/ApigeeEdgeTestTrait.php
> +    self::$modules[] = 'apigee_edge_test';
Use the new installExtraModules() method instead.

2018-07-12 10:55 UTC, mxr576 requested changes

2018-07-12 10:55 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +      $message = 'Connection failed. Response from Apigee Edge: %response';
The string is p~1 not translatable this way.

2018-07-12 12:58 UTC, mxr576 approved these changes

2018-07-12 13:03 UTC, merged