Detailed auth form messages, debug element
apigee/apigee-edge-drupal pull request #52
Opened 2018-07-19 07:22 UTC by peterserfozo

2018-07-19 11:11 UTC, mxr576 requested changes

2018-07-19 11:11 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +      $form['debug']['debug_text']['#access'] = TRUE;
Debug text does not have `#access` set to FALSE according to your code so this line should be unnecessary.

2018-07-19 11:11 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +          if ($curl_exception->getHandlerContext()['errno'] === 6) {
Use `CURLE_COULDNT_RESOLVE_HOST` instead.

2018-07-19 11:11 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +          if ($curl_exception->getHandlerContext()['errno'] === 28) {
Use `CURLE_OPERATION_TIMEDOUT` instead.

2018-07-19 11:11 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +          elseif ($curl_exception->getHandlerContext()['errno'] === 6) {
Use `CURLE_COULDNT_RESOLVE_HOST` instead.

2018-07-19 11:11 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +      $credentials['authorization_server'] = $key_type->getAuthorizationServer($key) ?? Oauth::DEFAULT_AUTHORIZATION_SERVER;
Why `getAuthorizationServer()` does not return `Oauth::DEFAULT_AUTHORIZATION_SERVER` if it has not been changed to something else? The same question for `getClientId()` and `getClientSecret()`. Would it be complicated to change the implementation? (IIRC we talked about something like this before)

2018-07-19 11:13 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +            '@fail_text' => $fail_text,
What if you would inject fail_text with `'!fail_text' => $fail_text->render()`? Using `Markup::create()` would be still necessary above?

2018-07-19 14:58 UTC, peterserfozo commented on src/Form/AuthenticationForm.php
> +      $form['debug']['debug_text']['#access'] = TRUE;
It has because `debug_text` is a child element of `debug`.

2018-07-23 12:13 UTC, mxr576 requested changes

2018-07-23 12:13 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +        if ($exception->getMessage() === 'Host can not be empty.') {
Message should be defined in a constant.

2018-07-23 12:13 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +            '%client_id' => $key_type->getClientId($key) ?? Oauth::DEFAULT_CLIENT_ID,
getClientId() never returns null.

2018-07-23 12:13 UTC, mxr576 commented on src/Form/AuthenticationForm.php
> +        if ($exception->getMessage() === 'Host can not be empty.') {
Btw, isn't there anything else specific in the exception that you can use in the condition? I do not really prefer writing a condition on an message that could change easily.

2018-07-23 12:14 UTC, mxr576 commented on tests/src/FunctionalJavascript/AuthenticationTest.php
> +    $this->assertSession()->pageTextNotContains('There is no available OAuth key for connecting to Apigee Edge.');
Why do not you define these specific message as constants in the test class at least? Copy-pasting the same message is not efficient.

2018-07-23 12:16 UTC, mxr576 commented on tests/src/FunctionalJavascript/AuthenticationTest.php
> +    // Only Apigee Edge keys are usable in SDK connector.
s/are usable/can be used/g

2018-07-23 12:16 UTC, mxr576 commented on tests/src/FunctionalJavascript/AuthenticationTest.php
> +      $this->assertSession()->pageTextContains('Debug information');
This text can also come from a constant in this test class.

2018-07-23 12:35 UTC, mxr576 approved these changes

2018-07-23 13:13 UTC, peterserfozo commented
Test: https://travis-ci.org/peterserfozo/apigee-edge-drupal/builds/407127955

2018-07-23 13:13 UTC, merged