Added the ability to autodetect Apigee organization for Hybrid
apigee/apigee-edge-drupal pull request #539
Opened 2020-12-17 06:34 UTC by giteshk

For hybrid we can figure out the organization that the current gcp project is connected to.

This is to improve the install experience on GCP

2020-12-20 16:29 UTC, mxr576 commented on src/Plugin/KeyInput/ApigeeAuthKeyInput.php
> + * Copyright 2020 Google Inc.
As far as I remember, the data here is when the file was created and not when the file was last modified. So it should not change #fixme.

2020-12-20 16:30 UTC, mxr576 commented on src/Plugin/KeyInput/ApigeeAuthKeyInput.php
> +          \Drupal::messenger()->addWarning("Apigee configuration has been auto detected. Please save this configuration. \n You may change this configuration to connect to a different Apigee organiza
Use HTML tags instead of `\n` to break text,

2020-12-20 16:31 UTC, mxr576 commented on src/Plugin/KeyInput/ApigeeAuthKeyInput.php
> +        $organization = array_pop($organizations);
What about the other orgs? What about the other available? (The method name indicates to me that there could be more). Why not just `$organization = reset($organizations);`?

2020-12-20 16:32 UTC, mxr576 requested changes

2020-12-20 16:32 UTC, mxr576 commented on src/Connector/GceServiceAccountAuthentication.php
> +    $sdk_connector = \Drupal::service('apigee_edge.sdk_connector');
Still, using dependency injection here would be useful, not just because the code could unit tested :)

2020-12-21 08:11 UTC, arlina-espinoza reviewed
Nice feature to add :) 
I agree with @mxr576 comments. Additionally, if this PR requires a fix on the PHP client (https://github.com/apigee/apigee-client-php/pull/114), it should also update the minimum required version in this module's composer file.

2021-01-19 20:43 UTC, raakesh-blokhra commented
@giteshk There is no issue associated with this pull request, and also the checks have failed. How do you plan to proceed with this? Do we need to close this?

2021-05-04 22:29 UTC, closed without merging