Change create app page path, breadcrumb fix
apigee/apigee-edge-drupal pull request #58
Opened 2018-08-01 09:21 UTC by peterserfozo

2018-08-01 09:53 UTC, mxr576 requested changes

2018-08-01 09:53 UTC, mxr576 commented on src/Breadcrumb/CreateAppForDeveloperBreadcrumbBuilder.php
> +      t('My @developer_app', [
Couldn't you leverage the `_title_callback` of the `entity.developer_app.collection_by_developer` route somehow here? This seems a code duplication to me and if the default page title changes in `\Drupal\apigee_edge\Controller\DeveloperAppListBuilderForDeveloper::getPageTitle` or the `_title_callback` of the route gets altered then the title of the page and what a user can see in the breadcrumb is not going to be aligned.

2018-08-01 09:53 UTC, mxr576 commented on tests/src/Functional/DeveloperAppUITestTrait.php
> +    $this->drupalPostForm(
Please add a test that ensures the custom breadcrumb is correct on the Add app form, this test should also validate if the custom breadcrumb works properly for different users (breadcrumb cache issue).

2018-08-01 09:53 UTC, mxr576 commented on apigee_edge.services.yml
> +    - { name: breadcrumb_builder, priority: 1001 }
Based on a quick query on the core and open social 101 should be enough as a default priority, we do not need to be this drastic :D

2018-08-02 05:17 UTC, mxr576 commented on apigee_edge.module
> +  $args['@developer_app'] = \Drupal::entityTypeManager()->getDefinition('developer_app')->getPluralLabel();
Please introduce a new alter hook that will allow to change the title of the My apps page consistently in all places where this function gets called. `_` wont't be needed anymore.

2018-08-02 05:21 UTC, mxr576 requested changes
Please fix the mentioned issue in my new comment.

2018-08-02 10:10 UTC, mxr576 requested changes

2018-08-02 10:10 UTC, mxr576 commented on apigee_edge.api.php
> +function hook_my_developer_apps_title_alter(TranslatableMarkup &$title, ?UserInterface $user = NULL) {
hook_apigee_edge_my....

2018-08-02 10:10 UTC, mxr576 commented on apigee_edge.api.php
> +use Drupal\Core\StringTranslation\TranslatableMarkup;
Always use the fully qualified class names in parameters, do not import them. See node.api.php (Let me know if it is not clear why).

2018-08-02 10:10 UTC, mxr576 commented on tests/modules/apigee_edge_test/apigee_edge_test.module
> +function apigee_edge_test_my_developer_apps_title_alter(TranslatableMarkup &$title, ?UserInterface $user = NULL) {
Do not forget to fix the name of the hook implementation here either :)

2018-08-02 10:10 UTC, mxr576 commented on apigee_edge.module
> +  \Drupal::moduleHandler()->alter('my_developer_apps_title', $title, $user);
So as said in our call... `apigee_edge_my_developer_apps_title` aka. `MODULE_NAME_hook`.

2018-08-02 10:35 UTC, mxr576 requested changes

2018-08-02 10:35 UTC, mxr576 commented on tests/modules/apigee_edge_test/apigee_edge_test.module
> + * Implements hook_my_developer_apps_title_alter().
You missed this one :P

2018-08-02 11:31 UTC, mxr576 approved these changes

2018-08-02 11:56 UTC, peterserfozo commented
Test: https://travis-ci.org/peterserfozo/apigee-edge-drupal/builds/411232200

2018-08-02 11:56 UTC, merged