Replaced deprecated "Formatter::formatResponse()" with "formatResponseForRequest" method
apigee/apigee-edge-drupal pull request #668
Opened 2022-02-14 13:22 UTC by shishir-intelli

Closes #667 
Replaced deprecated `Formatter::formatResponse()` with `formatResponseForRequest` method.
Reference : https://github.com/php-http/message/releases/tag/1.13.0

2022-02-16 14:39 UTC, phdhiren requested changes

2022-02-16 14:39 UTC, phdhiren commented on modules/apigee_edge_debug/src/Plugin/DebugMessageFormatter/DebugMessageFormatterPluginBase.php
> +    return $this->getFormatter()->formatResponseForRequest($response, $request);
This was just introduced in php-http/message:1.13
First need to update in apigee/apigee-client-php with this dependency version and that version should be updated here as well.

2022-02-22 07:33 UTC, shishir-intelli commented on modules/apigee_edge_debug/src/Plugin/DebugMessageFormatter/DebugMessageFormatterPluginBase.php
> +    return $this->getFormatter()->formatResponseForRequest($response, $request);
PR https://github.com/apigee/apigee-client-php/pull/207

2022-03-08 15:01 UTC, shishir-intelli commented on modules/apigee_edge_debug/src/Plugin/DebugMessageFormatter/DebugMessageFormatterPluginBase.php
> +    return $this->getFormatter()->formatResponseForRequest($response, $request);
PR (apigee_edge-drupal) https://github.com/apigee/apigee-edge-drupal/pull/675

2022-03-08 15:48 UTC, phdhiren approved these changes
LGTM

2022-03-08 17:07 UTC, merged