Team member sync
apigee/apigee-edge-drupal pull request #745
Opened 2022-10-18 08:42 UTC by divya-intelli

2022-10-19 15:03 UTC, giteshk commented on modules/apigee_edge_teams/apigee_edge_teams.routing.yml
> +    _title: 'Team Memeber Synchronization'
typo on Member

2022-11-01 08:23 UTC, shishir-intelli requested changes
@divya-intelli ,
`Team sync` functionality is working fine and updating data in the database, 
However on the Teams page I couldn't see more than 100 teams. It is still displaying only 100 teams even after changing the permission `View extensive teams list`

2022-11-01 10:48 UTC, divya-intelli commented
@shishir-intelli , the issue is fixed now, there was a bug in the condition which was restricted in displaying more than 100 teams. Please check.

2022-11-01 16:09 UTC, shishir-intelli reviewed
@divya-intelli 
Yes, It is working now, 
But it displays more than 100 teams only when the `View extensive teams list` permission is enabled ( #744 changes ) and Cache has not expired.

IMO, we should add some help text about enabling `View extensive teams list` permission and setting the `Cache` time limit here for more clarity. (`/admin/config/apigee-edge/app-settings/team-settings/sync`)
![image](https://user-images.githubusercontent.com/75600200/199279927-fc6bc216-acd8-4518-b599-d733451f0a99.png)

2022-11-02 14:23 UTC, shishir-intelli approved these changes

2022-11-16 15:21 UTC, merged